config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  devise_for :users 
  root 'welcome#index'
end

app/models/article.rb
  class Article < ActiveRecord::Base
  	# Esto es lo que se genero deesde la consola 
  	# Se puede decir que es la base de datos de Rails
  	# No se le dijo el nombre de la tabla va a toma
  	# el que se le dio a la clase en la terminal
  	# y tomo el nombre y lo pluraliso o le agrego la "S"
  	# y los campos los va agenara el Active Record
  	belongs_to :user
    has_many :comments  
  	validates :title, presence: true, uniqueness: true
  	validates :body, presence: true, length: { minimum: 10 }
    before_save :set_visits_count

    def update_visits_count
      self.save if self.visits_count.nil?
      self.update(visits_count: self.visits_count + 1)
    end

    private

    def set_visits_count
      self.visits_count ||= 0
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  	has_many :articles
  	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#before_action :validate_user, except: [:show,:index]
	#A ESTA RUTA SE ACCEDE CON: GET /articles
	before_action :authenticate_user!, except: [:show,:index]
	before_action :set_article, except: [:index,:new,:create] 
	def index 
		#Ob tiene todos los rgistros de la tabla Articles..
		@articles = Article.all
	end
	#GET /articles/:id
	def show 
		@article.update_visits_count
		#Encuen tra un registros segun el ID
		#@article = Article.find(params[:id])
		@comment = Comment.new
	end	
	#GET /articles/new 
	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id]) 
	end
	#POST /articles 
	def create 
		#Este es el Insert into
		#Esta es la antigua ->
		#@article = Article.new(title: params[:article][:title], body: params[:article][:title])
		@article = current_user.articles.new(article_params)
		if @article.save
			redirect_to @article
		else
		 	render :new
		end
	end
	def destroy
		#@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end	
	#PUT /articles/
	def update
	  	#@article = Article.find(params[:id])
	  	if  @article.update(article_params)
	  		redirect_to @article
	  	else
	  		render :edit
	  	end
	end 
	private
	#def validate_user
		#redirect_to new_user_session_path, notice: "Para agregar un articulo necesitas Iniciar Sesion"
	#end
	def set_article
		@article = Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title,:body)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div class="be-red white top-space">
			* <%= message %>
		</div>
	<%end%>
	<div class="field">
		<%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Escribe aqui el articulo", style:"height:200px;", class:"form-control" %>
	</div> 
	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white"%>
	</div>
<%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>Editar este articulo</h1>
		<%= render "form" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div>
		<%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class: "red"  %>
	</div>
<%end%>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>Crear articulo</h1>
	<%= form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div class="be-red white top-space">
			* <%= message %>
		</div>
	<%end%>
	<div class="field">
		<%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Escribe aqui el articulo", style:"height:200px;", class:"form-control" %>
	</div> 
	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white"%>
	</div>
<%end%>	
</div>

app/views/articles/show.html.erb
<h1><%=  @article.title %></h1>
<% unless @article.user.nil? %>
<p>
	Escrito por: <%= @article.user.email %>
</p>
<%end%>
<p>
	Visitas: <%= @article.visits_count %>
</p>
<div>
	<%= @article.body %>
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render "comments/form" %>
	<ul id="comments-box">
		<% @article.comments.each do |comment| %>
		<li>
			<%= comment.body %> - <%= comment.user.email %>
		</li>
		<%end%>
	</ul>
</div>
<div>
	<%= link_to "Editar", edit_article_path(@article) %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true, html: { id: "comments-form", :"data-type" => "json" }) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cnes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "partials/navegation"  %>
<p class="notice"><%= notice %></p>
	<p class="alert be-red"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/partials/_navegation.html.erb
<header>
	<nav class="be-red white large-padding">
		<ul class="no-list row center-xs middle-xs">
			<li type="none" class="logo col-md">
				<h1 class="no-margin">
					<%= link_to "CNestor", root_path %>
				</h1>
			</li>
			<li type="none" class="col-md">
				<%= link_to "Inicio", root_path %>
			</li>
			<li type="none" class="col-md">
				Diseño
			</li> 
			<li type="none" class="col-md" >
				Programación
			</li>
			<li type="none" class="col-md">
				Tecnologia
			</li>
			<% if user_signed_in? %>
				<li type="none" class="col-md">
					<%= link_to "Cerrar Sessión", destroy_user_session_path, method: :delete %>
				</li>
			<%else%>
			<li type="none" class="col-md">
					<%= link_to "Iniciar Sessión", new_user_session_path %>
				</li>
				<li type="none" class="col-md">
					<%= link_to "Crear Cuenta", new_user_registration_path %>
				</li>
			<%end%>
		</ul>
	</nav>
</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<h1>Bienvenido <%= current_user.email %> </h1>
<%end%>